#define TRAINER_NONE 0

#define TRAINER_RIVAL1                               1
// Route 1
#define TRAINER_ROUTE_1_YOUNGSTER_PETER              2
#define TRAINER_ROUTE_1_LASS_HELENA                  3
#define TRAINER_ROUTE_1_YOUNGSTER_HARLAN             4
// Route 2
#define TRAINER_ROUTE_2_YOUNGSTER_JOEY               5
#define TRAINER_ROUTE_2_LASS_KIMBERLY                6
#define TRAINER_ROUTE_2_LASS_RIKKI                   7
#define TRAINER_ROUTE_2_COOL_TRAINER_ANDY            16
// Varisi Forest
#define TRAINER_VARISI_FOREST_BUG_CATCHER_KENDELL    8
#define TRAINER_VARISI_FOREST_BUG_CATCHER_BRADEN     9
#define TRAINER_VARISI_FOREST_LASS_BREANNA           10
#define TRAINER_VARISI_FOREST_LASS_MIMI              11
// Rhodanzi City
#define TRAINER_RHODANZI_GYM_ALONSO                  12
#define TRAINER_RHODANZI_GYM_BRANDON                 13
#define TRAINER_RHODANZI_GYM_LEADER_TERRENCE         14
// Route 7
#define TRAINER_ROUTE_7_CAMPER_CARLISLE              15
// Route 8
#define TRAINER_ROUTE_3_PICKNICKER_TANA              17
#define TRAINER_ROUTE_3_BUG_CATCHER_IRWIN            18
#define TRAINER_ROUTE_3_YOUNGSTER_LOGAN              19
#define TRAINER_ROUTE_3_TWINS_NINA_AND_MEG           20
#define TRAINER_ROUTE_3_NINJA_BOY_BOTAN              21
#define TRAINER_ROUTE_3_ROCKER_JUDE                  22
