#define TRAINER_NONE 0

#define TRAINER_RIVAL1                               1
// Route 1
#define TRAINER_ROUTE_1_YOUNGSTER_PETER              2
#define TRAINER_ROUTE_1_LASS_HELENA                  3
#define TRAINER_ROUTE_1_YOUNGSTER_HARLAN             4
// Route 2
#define TRAINER_ROUTE_2_YOUNGSTER_JOEY               5
#define TRAINER_ROUTE_2_LASS_KIMBERLY                6
#define TRAINER_ROUTE_2_LASS_RIKKI                   7
// Varisi Forest
#define TRAINER_VARISI_FOREST_BUG_CATCHER_KENDELL    8
#define TRAINER_VARISI_FOREST_BUG_CATCHER_BRADEN     9
#define TRAINER_VARISI_FOREST_LASS_BREANNA           10
#define TRAINER_VARISI_FOREST_LASS_MIMI              11
// Rhodanzi City
#define TRAINER_RHODANZI_GYM_ALONSO                  12
#define TRAINER_RHODANZI_GYM_BRANDON                 13
#define TRAINER_RHODANZI_GYM_TERRENCE                14